name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 5222 -H 181.114.25.86 >> ~/.ssh/known_hosts

      - name: Ejecutar script de despliegue como root
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh -tt -o StrictHostKeyChecking=no -p 5222 admon@181.114.25.86 "cd /var/www/gpexcelencia && sudo ./deploy.sh"
